# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
