# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20160405_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date(mm-dd-yy)'),
        ),
    ]
